name: Update Priority Label

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5min a day
  issues:
    types: [labeled]

jobs:
  check_p0_label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check P0 label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/check_p0_label.py
