name: Change P0 label to P1 after 60 days

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 min. 

jobs:
  change_p0_label_to_p1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm install @octokit/rest
      
      - name: Change P0 label to P1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: sgowroji
          REPO: sgowroji/TestGitRepository
          P0_LABEL: 'P0'
          P1_LABEL: 'P1'
          AGE_THRESHOLD_DAYS: 60
        run: |
          node change-label.js
