name: Update issue priority

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Run every day at midnight

jobs:
  update-priority:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update issue priority
        uses: peter-evans/wait-action@v2.1.2 # Wait for 60 days before updating priority
        with:
          time: '0d'
          
      - name: Update issue priority
        uses: peter-evans/github-issues-automation@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: update
          label: P0
          new-label: P1
