name : Auto Change Priority P0 to P1

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change Priority P0 to P1
        uses: kubernetes-sigs/gateway-api/.github/workflows/change-priority-p0-to-p1.yaml@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days: 60
          label: 'P0'
          new-label: 'P1'
