name: Comment on Approved PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  comment-on-approved-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment on approved PR
        if: github.event.review.state == 'approved'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "This PR has been approved. Please merge when ready."
            });
