name: remind review
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  send_pull_requests:
    runs-on: ubuntu-latest
    name: list of pull requests
    steps:
      - name: listPullRequests
        uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: output
        run: echo '${{ steps.list.outputs.pulls }}'
