name: Comment on Approved PRs

on:
  schedule:
    - cron: '*/2 * * * *'  

jobs:
  comment-on-approved-prs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get all open pull requests
      id: get_prs
      run: |
        echo "::set-output name=prs::$(curl -s -H \"Accept: application/vnd.github.v3+json\" https://api.github.com/repos/${{ github.repository }}/pulls?state=open | jq '.[] | select(.state == \"open\") | {number: .number, created_at: .created_at, user: .user.login, head_sha: .head.sha, approved_reviewers: [ .requested_reviewers[]?.login, .reviews[]?.user.login ] | unique }' | jq -s '.')"

    - name: Comment on approved PRs
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prs = ${{ steps.get_prs.outputs.prs }};
          const now = new Date();
          const dayInMillis = 1000 * 60 * 60 * 24;
          for (const pr of prs) {
            const createdAt = new Date(pr.created_at);
              const comment = `This pull request was approved more than a day ago. Thank you for your contribution! :smile: :+1:`;
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: comment
              });
          }
