name: Comment on Approved Pull Request

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every day at midnight

jobs:
  comment_on_approved_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Install Dependencies
        run: npm install

      - name: Comment on Approved Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const script = require('./\.github/workflows/scripts/merge.js')
            script({github, context})
